EmployeeManagement/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EmployeeManagement.DAL
{
    public class Employee
    {
        public int id { get; set; }
        public string employee_name { get; set; }
        public decimal employee_salary { get; set; }
        public int employee_age { get; set; }
        public string profile_image { get; set; }
    }
}

EmployeeManagement/Controllers/EmployeeController.cs
using EmployeeManagement.DAL;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Index()
        {
            var dtEmployee = new DataTable();
            var client = new HttpClient();

            client.DefaultRequestHeaders.Add("User-Agent", "C# console program");
            client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

            var url = "http://dummy.restapiexample.com/api/v1/employees";
            System.Threading.Thread.Sleep(5000);
            HttpResponseMessage response = await client.GetAsync(url);
            response.EnsureSuccessStatusCode();
            var resp = await response.Content.ReadAsStringAsync();
            var result = JObject.Parse(resp);
            var items = result["data"].Children().ToList();

            dtEmployee.Columns.Add("id");
            dtEmployee.Columns.Add("employee_name");
            dtEmployee.Columns.Add("employee_salary");
            dtEmployee.Columns.Add("employee_age");
            dtEmployee.Columns.Add("profile_image");
            dtEmployee.Columns.Add("average_age");
            dtEmployee.Columns.Add("average_salary");
            foreach (var subItem in items)
            {
                dtEmployee.Rows.Add(new object[] { subItem["id"], subItem["employee_name"], subItem["employee_salary"], subItem["employee_age"], subItem["profile_image"] });
            }
            int AverageAge = decimal.ToInt32(dtEmployee.Select().Where(p => p["employee_age"] != null).Select(c => Convert.ToDecimal(c["employee_age"])).Average());
            decimal AverageSalary = Math.Round(dtEmployee.Select().Where(p => p["employee_salary"] != null).Select(c => Convert.ToDecimal(c["employee_salary"])).Average(), 2);
            foreach (DataRow row in dtEmployee.Rows)
            {
                if (Convert.ToDecimal(row["employee_salary"]) > AverageSalary)
                {
                    row["average_salary"] = "Above";
                }
                else if (Convert.ToDecimal(row["employee_salary"]) < AverageSalary)
                {
                    row["average_salary"] = "Below";
                }
                else
                {
                    row["average_salary"] = "Equal";
                }
                if (Convert.ToInt32(row["employee_age"]) > AverageAge)
                {
                    row["average_age"] = "Above";
                }
                else if (Convert.ToInt32(row["employee_age"]) < AverageAge)
                {
                    row["average_age"] = "Below";
                }
                else
                {
                    row["average_age"] = "Equal";
                }
            }
            ViewBag.AverageAge = AverageAge;
            ViewBag.AverageSalary = AverageSalary;
            ViewBag.dtEmployee = dtEmployee;

            return View();
        }


        // GET: Employee/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EmployeeManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EmployeeManagement/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h3>Average Age Of Employees:<b> @ViewBag.AverageAge</b> </h3>
<br />
<h3>Average Salary Of Employees: <b> @ViewBag.AverageSalary</b></h3>
<br />

<table class="table table-bordered table-striped">
    <tr>
        <th>Name</th>
        <th>Salary</th>
        <th>Above/Below the average salary</th>
        <th>Age</th>
        <th>Above/Below the average age</th>
        <th>Image</th>
    </tr>
    @for (int i = 0; i < @ViewBag.dtEmployee.Rows.Count; i++)
    {
        <tr>
            <td>@ViewBag.dtEmployee.Rows[i]["employee_name"]</td>
            <td>@ViewBag.dtEmployee.Rows[i]["employee_salary"]</td>
            <td>@ViewBag.dtEmployee.Rows[i]["average_salary"]</td>
            <td>@ViewBag.dtEmployee.Rows[i]["employee_age"]</td>
            <td>@ViewBag.dtEmployee.Rows[i]["average_age"]</td>
            <td>@ViewBag.dtEmployee.Rows[i]["profile_image"]</td>
        </tr>
    }
</table>

EmployeeManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EmployeeManagement/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EmployeeManagement/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Employee Details</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Detail", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>